# Generated by Django 6.0.3 on 2026-03-29 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icone', models.CharField(default='🏗️', max_length=50)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('condicao', models.CharField(choices=[('usada', 'Usada'), ('seminova', 'Seminova'), ('nova', 'Nova')], default='nova', max_length=20)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=12)),
                ('preco_promocional', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('descricao', models.TextField()),
                ('especificacoes', models.TextField(blank=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='Maquinas/')),
                ('estoque', models.IntegerField(default=1)),
                ('destaque', models.BooleanField(default=False)),
                ('disponivel', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Maquinas', to='catalogo.categoria')),
            ],
        ),
    ]
