# Generated by Django 6.0.3 on 2026-03-29 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nome'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='maquina',
            options={'ordering': ['nome'], 'verbose_name': 'Máquina', 'verbose_name_plural': 'Máquinas'},
        ),
        migrations.AlterField(
            model_name='maquina',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maquinas', to='catalogo.categoria'),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='condicao',
            field=models.CharField(choices=[('nova', 'Nova'), ('seminova', 'Seminova'), ('usada', 'Usada')], default='nova', max_length=20),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='maquinas/'),
        ),
    ]
